<?php
/**
 * Compact GTranslate shortcode wrapper.
 *
 * @package GeneratePress_Child
 */

defined( 'ABSPATH' ) || exit;

/**
 * Render a compact GTranslate switcher.
 *
 * Shortcode:
 * [annam_language_switcher]
 * [annam_language_switcher look="dropdown"]
 *
 * @param array<string,mixed> $atts Shortcode attributes.
 * @return string
 */
function annam_language_switcher_shortcode( $atts = array() ) {
	$atts = shortcode_atts(
		array(
			'look'        => 'dropdown',
			'class'       => '',
			'aria_label'  => __( 'Chọn ngôn ngữ', 'generatepress_child' ),
		),
		is_array( $atts ) ? $atts : array(),
		'annam_language_switcher'
	);

	if ( ! class_exists( 'GTranslate' ) || ! method_exists( 'GTranslate', 'get_widget_code' ) ) {
		return '';
	}

	$look = sanitize_key( (string) $atts['look'] );
	$globe_icon = function_exists( 'strip_theme_get_svg' ) ? strip_theme_get_svg( 'globe' ) : '';

	static $instance = 0;
	$instance++;
	$unique_id = 'annam-language-switcher-' . $instance;
	$classes   = array(
		'annam-language-switcher',
		'annam-language-switcher--custom',
		'annam-language-switcher--' . $look,
		'notranslate',
	);
	if ( '' !== trim( (string) $atts['class'] ) ) {
		$extra_classes = preg_split( '/\s+/', trim( (string) $atts['class'] ) );
		if ( is_array( $extra_classes ) ) {
			foreach ( $extra_classes as $extra_class ) {
				$extra_class = sanitize_html_class( $extra_class );
				if ( '' !== $extra_class ) {
					$classes[] = $extra_class;
				}
			}
		}
	}

	$data = get_option( 'GTranslate' );
	GTranslate::load_defaults( $data );

	$normalize_languages = static function ( $languages ) {
		if ( ! is_array( $languages ) ) {
			return array();
		}

		$languages = array_values( array_unique( array_filter( array_map( 'sanitize_text_field', $languages ) ) ) );

		return $languages;
	};

	$default_plugin_languages = array( 'en', 'es', 'it', 'pt', 'de', 'fr', 'ru', 'nl', 'ar', 'zh-CN' );
	$incl_languages           = $normalize_languages( isset( $data['incl_langs'] ) ? $data['incl_langs'] : array() );
	$fincl_languages          = $normalize_languages( isset( $data['fincl_langs'] ) ? $data['fincl_langs'] : array() );

	if ( $incl_languages === $default_plugin_languages && $fincl_languages !== $default_plugin_languages && ! empty( $fincl_languages ) ) {
		$languages = $fincl_languages;
	} elseif ( $fincl_languages === $default_plugin_languages && $incl_languages !== $default_plugin_languages && ! empty( $incl_languages ) ) {
		$languages = $incl_languages;
	} elseif ( ! empty( $incl_languages ) && ! empty( $fincl_languages ) ) {
		$intersection = array_values( array_unique( array_intersect( $incl_languages, $fincl_languages ) ) );
		$languages    = ! empty( $intersection )
			? $intersection
			: ( count( $incl_languages ) <= count( $fincl_languages ) ? $incl_languages : $fincl_languages );
	} elseif ( ! empty( $incl_languages ) ) {
		$languages = $incl_languages;
	} else {
		$languages = $fincl_languages;
	}

	if ( empty( $languages ) ) {
		$languages = array( (string) $data['default_language'] );
	}

	if ( ! in_array( (string) $data['default_language'], $languages, true ) ) {
		array_unshift( $languages, (string) $data['default_language'] );
		$languages = array_values( array_unique( $languages ) );
	}

	$lang_names = ! empty( $data['native_language_names'] )
		? json_decode( GTranslate::$lang_array_native_json, true )
		: GTranslate::$lang_array;

	if ( ! is_array( $lang_names ) ) {
		$lang_names = GTranslate::$lang_array;
	}

	$current_code  = (string) $data['default_language'];
	$current_label = isset( $lang_names[ $current_code ] ) ? (string) $lang_names[ $current_code ] : strtoupper( $current_code );

	if ( isset( $_SERVER['HTTP_X_GT_LANG'] ) ) {
		$server_lang = sanitize_text_field( wp_unslash( (string) $_SERVER['HTTP_X_GT_LANG'] ) );
		if ( in_array( $server_lang, $languages, true ) ) {
			$current_code  = $server_lang;
			$current_label = isset( $lang_names[ $current_code ] ) ? (string) $lang_names[ $current_code ] : strtoupper( $current_code );
		}
	}

	$menu_items = array();
	foreach ( $languages as $language ) {
		if ( ! isset( $lang_names[ $language ] ) ) {
			continue;
		}

		$item = GTranslate::render_single_item(
			array(
				'lang'        => $language,
				'widget_look' => 'lang_names',
				'label'       => $lang_names[ $language ],
			)
		);

		if ( '' === $item ) {
			continue;
		}

		$item_classes = array( 'annam-language-switcher__item' );
		if ( $language === $current_code ) {
			$item_classes[] = 'gt-current-lang';
		}

		$menu_items[] = sprintf(
			'<li class="%1$s">%2$s</li>',
			esc_attr( implode( ' ', $item_classes ) ),
			$item // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Output is generated by GTranslate and intentionally returned as HTML.
		);
	}

	if ( empty( $menu_items ) ) {
		return '';
	}

	return sprintf(
		'<details id="%1$s" class="%2$s"><summary class="annam-language-switcher__trigger" aria-label="%3$s"><span class="annam-language-switcher__trigger-icon" aria-hidden="true">%8$s</span><span class="annam-language-switcher__trigger-label">%4$s</span><span class="annam-language-switcher__trigger-caret" aria-hidden="true"></span></summary><div class="annam-language-switcher__dropdown" role="listbox" aria-label="%3$s"><div class="annam-language-switcher__dropdown-head"><span class="annam-language-switcher__dropdown-label">%5$s</span><span class="annam-language-switcher__dropdown-value" data-annam-language-current="%1$s" data-default-lang="%6$s" data-default-label="%4$s">%4$s</span></div><ul class="annam-language-switcher__menu">%7$s</ul></div></details>',
		esc_attr( $unique_id ),
		esc_attr( implode( ' ', array_filter( $classes ) ) ),
		esc_attr( (string) $atts['aria_label'] ),
		esc_html( $current_label ),
		esc_html__( 'Ngôn ngữ hiện tại', 'generatepress_child' ),
		esc_attr( $current_code ),
		implode( '', $menu_items ), // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Output is generated by GTranslate and intentionally returned as HTML.
		$globe_icon // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Local SVG asset.
	);
}
add_shortcode( 'annam_language_switcher', 'annam_language_switcher_shortcode' );
